Repository coq-community/docker-coq-action, pull requests merged in 2020-04, with the labels that each got.

#5 Support time-group feature
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  README.md
  action.yml
  entrypoint.sh
  helper.sh
  timegroup.sh
Labels: enhancement

#8 Simplify entrypoint
  .github/workflows/reviewdog.yml
  action.yml
  entrypoint.sh
Labels: enhancement

#9 Document build matrix
  README.md
Labels: documentation

#10 Support custom images such as https://hub.docker.com/u/mathcomp
  README.md
  action.yml
  entrypoint.sh
Labels: enhancement

#11 First complete version of docker-coq-action
  .dockerignore
  .github/workflows/reviewdog.yml
  .gitignore
  Dockerfile
  Makefile
  README.md
  action.yml
  entrypoint.sh
  helper.sh
  timegroup.sh
Labels: feature

#15 Update reviewdog config
  .github/workflows/reviewdog.yml
Labels: fix

#13 Improve README.md
  README.md
Labels: documentation

#14 Support coq-problem-matcher
  .dockerignore
  Dockerfile
  README.md
  action.yml
  coq.json
  entrypoint.sh
Labels: feature

#16 docs: Add badge+link mentioning the example repo
  README.md
Labels: documentation
